project/Models/ErrorViewModel.cs
namespace project.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

project/Models/User.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.Data.SqlClient;

namespace project.Models
{
    public class User
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [MaxLength(50)]
        public string Name { get; set; }

        [Required]
        [MaxLength(50)]
        public string Email { get; set; }

        [Required]
        [MaxLength(10)]
        public string Number { get; set; }

        [Required]
        public string Password { get; set; }
        [Required]
        public string ConfirmPassword { get; set; }
    }
}

project/Models/User_login.cs
using System.ComponentModel.DataAnnotations;

namespace project.Models
{
    public class User_login
    {
        public int Id { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [MaxLength(50)]
        public string Password { get; set; }
    }
}

project/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using project.Models;
using System.Diagnostics;

namespace project.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

project/Controllers/WebController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using project.Data;
using project.Models;

namespace project.Controllers
{
    public class WebController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WebController(ApplicationDbContext _context)
        {
                this._context = _context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Home()
        {
            IEnumerable<User> users = _context .Users;
            return View(users);
            
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Menu()
        {
            return View();
        }
        public IActionResult Orders()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(User_login model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _context.Users.FirstOrDefaultAsync(u => u.Email == model.Email && u.Password == model.Password);
            HttpContext.Session.SetString("Email", model.Email);
            if (user != null)
            {
                // Log in the user
                // Redirect to home page or any other page after successful login
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Incorrect username or password");
                return View(model);
            }
        }

        //---------------------------------------------------------------------
        [HttpGet]
        public IActionResult Registration()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Registration(User user)
        {
            if (ModelState.IsValid)
            {
                var existingUser = _context.Users.FirstOrDefault(u => u.Email == user.Email || u.Number == user.Number);
                if (existingUser != null)
                {
                    ModelState.AddModelError("", "Email or number already exists!");
                    return View();
                }

                if (user.Password != user.ConfirmPassword)
                {
                    ModelState.AddModelError("", "Confirm password not matched!");
                    return View();
                }

                user.Password = HashPassword(user.Password); // Implement hash function as needed

                _context.Users.Add(user);
                _context.SaveChanges();

                // Redirect to home or login page
                return RedirectToAction("Index", "Home");
            }

            return View(user);
        }
        private string HashPassword(string password)
        {
            // Implement your password hashing logic here
            return password; // For demonstration, return plain password
        }
        ////public IActionResult Registration()
        ////{
        ////    return View();
        ////}

        //---------------------------------------------------------------
        public IActionResult ShoppingCart()
        {
            return View();
        }
        public IActionResult MyProfile()
        {
            return View();
        }
        public IActionResult CheCkout()
        {
            return View();
        }
        public IActionResult YourAddress()
        {
            return View();
        }
        public IActionResult UpdateProfile()
        {
            return View();
        }
        public IActionResult Search()
        {
            return View();
        }
    }
}

project/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<link rel="stylesheet" href="~/css/style.css" asp-append-version="true"   />
<link rel="stylesheet" href="~/js/site.js" asp-append-version="true"   />

<link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css" />

<!-- font awesome cdn link  -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

<header class="header">

    <section class="flex">

        <a href="/Web/Home" class="logo">yum-yum 😋</a>

        <nav class="navbar">
            <a href="/Web/Home">Home</a>
            <a href="/Web/About">about</a>
            <a href="/Web/Menu">menu</a>
            <a href="/Web/Orders">orders</a>
            <a href="/Web/Contact">contact</a>
        </nav>

        <div class="icons">
            <a href="/Web/Search"><i class="fas fa-search"></i></a>
            <a href="/Web/ShoppingCart"><i class="fas fa-shopping-cart"></i><span>(3)</span></a>
            <div id="user-btn" class="fas fa-user"></div>
            <div id="menu-btn" class="fas fa-bars"></div>
        </div>

        <div class="profile">
            <p class="name">
                @if (Context.Session.GetString("Email")==null)
                {
                    
                }
                else
                {
                    Context.Session.GetString("Email");
                }
                    </p>
            <div class="flex">
                <a href="/Web/MyProfile" class="btn">profile</a>
                <a href="#" class="delete-btn">logout</a>
            </div>
            <p class="account"><a href="/Web/Login">login</a> or <a href="/Web/Registration">register</a></p>
        </div>

    </section>

</header>




<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Web" asp-action="Home">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

project/Views/Web/About.cshtml
@{
    ViewData["Title"] = "About";
}
<link rel="stylesheet" href="~/css/style.css" asp-append-version="true"   />
<link rel="stylesheet" href="~/js/site.js" asp-append-version="true"   />

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>about us</title>

   <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css" />

   <!-- font awesome cdn link  -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

   <!-- custom css file link  -->
   <link rel="stylesheet" href="css/style.css">

</head>
<body>

    <header class="header">

        <section class="flex">

            <a href="/Web/Home" class="logo">yum-yum 😋</a>

            <nav class="navbar">
                <a href="/Web/Home">Home</a>
                <a href="/Web/About">about</a>
                <a href="/Web/Menu">menu</a>
                <a href="/Web/Orders">orders</a>
                <a href="/Web/Contact">contact</a>
            </nav>

            <div class="icons">
                <a href="/Web/Search"><i class="fas fa-search"></i></a>
                <a href="/Web/ShoppingCart"><i class="fas fa-shopping-cart"></i><span>(3)</span></a>
                <div id="user-btn" class="fas fa-user"></div>
                <div id="menu-btn" class="fas fa-bars"></div>
            </div>

            <div class="profile">
                <p class="name">Axit Gadhiya</p>
                <div class="flex">
                    <a href="/Web/MyProfile" class="btn">profile</a>
                    <a href="#" class="delete-btn">logout</a>
                </div>
                <p class="account"><a href="/Web/Login">login</a> or <a href="/Web/Registration">register</a></p>
            </div>

        </section>

    </header>

<div class="heading">
   <h3>about us</h3>
        <p><a href="/Web/Home">Home </a> <span> / about</span></p>
</div>

<section class="about">

   <div class="row">

      <div class="image">
         <img src="~/images/about-img.svg" alt="">
      </div>

      <div class="content">
         <h3>why choose us?</h3>
         <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis non odit nihil, doloremque sunt aut placeat culpa. Adipisci minima, neque necessitatibus incidunt nemo eveniet mollitia quis facere vel consectetur culpa?</p>
                <a href="/Web/Menu" class="btn">our menu</a>
      </div>

   </div>

</section>

<section class="steps">

   <h1 class="title">3 simple steps</h1>

   <div class="box-container">

      <div class="box">
         <img src="~/images/step-1.png" alt="">
         <h3>select food</h3>
         <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, hic.</p>
      </div>

      <div class="box">
         <img src="~/images/step-2.png" alt="">
         <h3>30 minutes delivery</h3>
         <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, hic.</p>
      </div>

      <div class="box">
         <img src="~/images/step-3.png" alt="">
         <h3>enjoy food!</h3>
         <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, hic.</p>
      </div>

   </div>

</section>

<section class="reviews">

   <h1 class="title">customer's reviews</h1>

   <div class="swiper reviews-slider">

      <div class="swiper-wrapper">

         <div class="swiper-slide slide">
            <img src="~/images/pic-1.png" alt="">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo exercitationem ullam esse quia iusto in.</p>
            <div class="stars">
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star-half-alt"></i>
            </div>
            <h3>john deo</h3>
         </div>

         <div class="swiper-slide slide">
            <img src="~/images/pic-2.png" alt="">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo exercitationem ullam esse quia iusto in.</p>
            <div class="stars">
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star-half-alt"></i>
            </div>
            <h3>john deo</h3>
         </div>

         <div class="swiper-slide slide">
            <img src="~/images/pic-3.png" alt="">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo exercitationem ullam esse quia iusto in.</p>
            <div class="stars">
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star-half-alt"></i>
            </div>
            <h3>john deo</h3>
         </div>

         <div class="swiper-slide slide">
            <img src="~/images/pic-4.png" alt="">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo exercitationem ullam esse quia iusto in.</p>
            <div class="stars">
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star-half-alt"></i>
            </div>
            <h3>john deo</h3>
         </div>

         <div class="swiper-slide slide">
            <img src="~/images/pic-5.png" alt="">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo exercitationem ullam esse quia iusto in.</p>
            <div class="stars">
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star-half-alt"></i>
            </div>
            <h3>john deo</h3>
         </div>

         <div class="swiper-slide slide">
            <img src="~/images/pic-6.png" alt="">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo exercitationem ullam esse quia iusto in.</p>
            <div class="stars">
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star-half-alt"></i>
            </div>
            <h3>john deo</h3>
         </div>

      </div>

      <div class="swiper-pagination"></div>

   </div>

</section>





















    <footer class="footer">

        <section class="box-container">

            <div class="box">
                <img src="~/images/email-icon.png" alt="">
                <h3>our email</h3>
                <a href="mailto:gadhiyaaxit@gmail.com">gadhiyaaxit@gmail.com</a>
                <a href="mailto:agadhiya975@rku.ac.in">agadhiya975@rku.ac.in</a>
            </div>

            <div class="box">
                <img src="~/images/clock-icon.png" alt="">
                <h3>opening hours</h3>
                <p>00:07am to 00:10pm </p>
            </div>

            <div class="box">
                <img src="~/images/map-icon.png" alt="">
                <h3>our address</h3>
                <a href="https://www.google.com/maps">Rajkot, india - 360003</a>
            </div>

            <div class="box">
                <img src="~/images/phone-icon.png" alt="">
                <h3>our number</h3>
                <a href="tel:1234567890">+123-456-7890</a>
                <a href="tel:1112223333">+111-222-3333</a>
            </div>

        </section>

        <div class="credit">&copy; copyright 2024 by <span>Mr.Axit Gadhiya</span> | all rights reserved!</div>

    </footer>







<div class="loader">
   <img src="~/images/loader.gif" alt="">
</div>

<script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>



<script>

var swiper = new Swiper(".reviews-slider", {
   loop:true,
   grabCursor:true,
            spaceBetween: 20,
   pagination: {
      el: ".swiper-pagination",
   },
   breakpoints: {
      550: {
        slidesPerView: 1,
      },
      768: {
        slidesPerView: 2,
      },
      1024: {
        slidesPerView: 3,
      },
   },
});

</script>

</body>
</html>

project/Views/Web/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<link rel="stylesheet" href="~/css/style.css" asp-append-version="true"   />
<link rel="stylesheet" href="~/js/site.js" asp-append-version="true"   />

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>contact us</title>

   <!-- font awesome cdn link  -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

   <!-- custom css file link  -->
   <link rel="stylesheet" href="css/style.css">

</head>
<body>

    <header class="header">

        <section class="flex">

            <a href="/Web/Home" class="logo">yum-yum 😋</a>

            <nav class="navbar">
                <a href="/Web/Home">Home</a>
                <a href="/Web/About">about</a>
                <a href="/Web/Menu">menu</a>
                <a href="/Web/Orders">orders</a>
                <a href="/Web/Contact">contact</a>
            </nav>

            <div class="icons">
                <a href="/Web/Search"><i class="fas fa-search"></i></a>
                <a href="/Web/ShoppingCart"><i class="fas fa-shopping-cart"></i><span>(3)</span></a>
                <div id="user-btn" class="fas fa-user"></div>
                <div id="menu-btn" class="fas fa-bars"></div>
            </div>

            <div class="profile">
                <p class="name">Axit Gadhiya</p>
                <div class="flex">
                    <a href="/Web/MyProfile" class="btn">profile</a>
                    <a href="#" class="delete-btn">logout</a>
                </div>
                <p class="account"><a href="/Web/Login">login</a> or <a href="/Web/Registration">register</a></p>
            </div>

        </section>

    </header>

<div class="heading">
   <h3>contact us</h3>
        <p><a href="/Web/Home">Home </a> <span> / contact</span></p>
</div>

<section class="contact">

   <div class="row">

      <div class="image">
         <img src="~/images/contact-img.svg" alt="">
      </div>

      <form action="" method="post">
         <h3>tell us something!</h3>
         <input type="text" name="name" required placeholder="enter your name" maxlength="50" class="box">
         <input type="number" name="number" required placeholder="enter your number" max="9999999999" min="0" class="box" onkeypress="if(this.value.length == 10) return false;">
         <input type="email" name="email" required placeholder="enter your email" maxlength="50" class="box">
         <textarea name="msg" placeholder="enter your message" required class="box" cols="30" rows="10" maxlength="500"></textarea>
         <input type="submit" value="send message" class="btn" name="send">
      </form>

   </div>

</section>


























    <footer class="footer">

        <section class="box-container">

            <div class="box">
                <img src="~/images/email-icon.png" alt="">
                <h3>our email</h3>
                <a href="mailto:gadhiyaaxit@gmail.com">gadhiyaaxit@gmail.com</a>
                <a href="mailto:agadhiya975@rku.ac.in">agadhiya975@rku.ac.in</a>
            </div>

            <div class="box">
                <img src="~/images/clock-icon.png" alt="">
                <h3>opening hours</h3>
                <p>00:07am to 00:10pm </p>
            </div>

            <div class="box">
                <img src="~/images/map-icon.png" alt="">
                <h3>our address</h3>
                <a href="https://www.google.com/maps">Rajkot, india - 360003</a>
            </div>

            <div class="box">
                <img src="~/images/phone-icon.png" alt="">
                <h3>our number</h3>
                <a href="tel:1234567890">+123-456-7890</a>
                <a href="tel:1112223333">+111-222-3333</a>
            </div>

        </section>

        <div class="credit">&copy; copyright 2024 by <span>Mr.Axit Gadhiya</span> | all rights reserved!</div>

    </footer>


<div class="loader">
   <img src="~/images/loader.gif" alt="">
</div>

</body>
</html>

project/Views/Web/Login.cshtml
@model project.Models.User_login
@{
    ViewData["Title"] = "Login";
}

<link rel="stylesheet" href="~/css/style.css" asp-append-version="true"   />
<link rel="stylesheet" href="~/js/site.js" asp-append-version="true"   />

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>login</title>

   <!-- font awesome cdn link  -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

   <!-- custom css file link  -->
   <link rel="stylesheet" href="css/style.css">

</head>
<body>

    <header class="header">

        <section class="flex">

            <a href="/Web/Home" class="logo">yum-yum 😋</a>

            <nav class="navbar">
                <a href="/Web/Home">Home</a>
                <a href="/Web/About">about</a>
                <a href="/Web/Menu">menu</a>
                <a href="/Web/Orders">orders</a>
                <a href="/Web/Contact">contact</a>
            </nav>

            <div class="icons">
                <a href="/Web/Search"><i class="fas fa-search"></i></a>
                <a href="/Web/ShoppingCart"><i class="fas fa-shopping-cart"></i><span>(3)</span></a>
                <div id="user-btn" class="fas fa-user"></div>
                <div id="menu-btn" class="fas fa-bars"></div>
            </div>

            <div class="profile">
                <p class="name">Axit Gadhiya</p>
                <div class="flex">
                    <a href="/Web/MyProfile" class="btn">profile</a>
                    <a href="#" class="delete-btn">logout</a>
                </div>
                <p class="account"><a href="/Web/Login">login</a> or <a href="/Web/Registration">register</a></p>
            </div>

        </section>

    </header>


<section class="form-container">

        <form asp-action="Login" method="post" asp-controller="Web">
            <h3>login now</h3>
            <input asp-for="Email" type="email" required maxlength="50" placeholder="enter your email" class="box" oninput="this.value = this.value.replace(/\s/g, '')">
            <input asp-for="Password" type="password" required maxlength="20" placeholder="enter your password" class="box" oninput="this.value = this.value.replace(/\s/g, '')">
            <input type="submit" value="login now" class="btn" name="submit">
            <a asp-action="Home" asp-controller="Web">back to register</a>
            <p>don't have an account? <a href="/web/Registration">register now</a></p>
        </form> 


</section>























    <footer class="footer">

        <section class="box-container">

            <div class="box">
                <img src="~/images/email-icon.png" alt="">
                <h3>our email</h3>
                <a href="mailto:gadhiyaaxit@gmail.com">gadhiyaaxit@gmail.com</a>
                <a href="mailto:agadhiya975@rku.ac.in">agadhiya975@rku.ac.in</a>
            </div>

            <div class="box">
                <img src="~/images/clock-icon.png" alt="">
                <h3>opening hours</h3>
                <p>00:07am to 00:10pm </p>
            </div>

            <div class="box">
                <img src="~/images/map-icon.png" alt="">
                <h3>our address</h3>
                <a href="https://www.google.com/maps">Rajkot, india - 360003</a>
            </div>

            <div class="box">
                <img src="~/images/phone-icon.png" alt="">
                <h3>our number</h3>
                <a href="tel:1234567890">+123-456-7890</a>
                <a href="tel:1112223333">+111-222-3333</a>
            </div>

        </section>

        <div class="credit">&copy; copyright 2024 by <span>Mr.Axit Gadhiya</span> | all rights reserved!</div>

    </footer>



<div class="loader">
   <img src="images/loader.gif" alt="">
</div>

</body>
</html>

project/Views/Web/Registration.cshtml
@model project.Models.User
@{
    ViewData["Title"] = "Registration";
}
<link rel="stylesheet" href="~/css/style.css" asp-append-version="true"   />
<link rel="stylesheet" href="~/js/site.js" asp-append-version="true"   />

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>register</title>

   <!-- font awesome cdn link  -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

   <!-- custom css file link  -->
   <link rel="stylesheet" href="css/style.css">

</head>
<body>

    <header class="header">

        <section class="flex">

            <a href="/Web/Home" class="logo">yum-yum 😋</a>

            <nav class="navbar">
                <a href="/Web/Home">Home</a>
                <a href="/Web/About">about</a>
                <a href="/Web/Menu">menu</a>
                <a href="/Web/Orders">orders</a>
                <a href="/Web/Contact">contact</a>
            </nav>

            <div class="icons">
                <a href="/Web/Search"><i class="fas fa-search"></i></a>
                <a href="/Web/ShoppingCart"><i class="fas fa-shopping-cart"></i><span>(3)</span></a>
                <div id="user-btn" class="fas fa-user"></div>
                <div id="menu-btn" class="fas fa-bars"></div>
            </div>

            <div class="profile">
                <p class="name">Axit Gadhiya</p>
                <div class="flex">
                    <a href="/Web/MyProfile" class="btn">profile</a>
                    <a href="#" class="delete-btn">logout</a>
                </div>
                <p class="account"><a href="/Web/Login">login</a> or <a href="/Web/Registration">register</a></p>
            </div>

        </section>

    </header>

<section class="form-container">

        <form asp-action="Registration" method="post" asp-controller="Web">
            <h3>register now</h3>
            <input asp-for="Name" type="text" required maxlength="20" placeholder="enter your name" class="box" oninput="this.value = this.value.replace(/\s/g, '')">
            <input asp-for="Email" type="email" required maxlength="50" placeholder="enter your email" class="box" oninput="this.value = this.value.replace(/\s/g, '')">
            <input asp-for="Number" type="number" min="0" max="9999999999" onkeypress="if(this.value.length == 10) return false;" placeholder="enter your number" required class="box">
            <input asp-for="Password" type="password" required maxlength="20" placeholder="enter your password" class="box" oninput="this.value = this.value.replace(/\s/g, '')">
            <input asp-for="ConfirmPassword" type="password" required maxlength="20" placeholder="confirm your password" class="box" oninput="this.value = this.value.replace(/\s/g, '')">
            <button type="submit" value="register now" class="btn" name="submit">register</button>
            <a asp-action="Home" asp-controller="Web">back to register</a>
            <p>already have an account? <a href="/web/Login">login now</a></p>
        </form>

</section>

























    <footer class="footer">

        <section class="box-container">

            <div class="box">
                <img src="~/images/email-icon.png" alt="">
                <h3>our email</h3>
                <a href="mailto:gadhiyaaxit@gmail.com">gadhiyaaxit@gmail.com</a>
                <a href="mailto:agadhiya975@rku.ac.in">agadhiya975@rku.ac.in</a>
            </div>

            <div class="box">
                <img src="~/images/clock-icon.png" alt="">
                <h3>opening hours</h3>
                <p>00:07am to 00:10pm </p>
            </div>

            <div class="box">
                <img src="~/images/map-icon.png" alt="">
                <h3>our address</h3>
                <a href="https://www.google.com/maps">Rajkot, india - 360003</a>
            </div>

            <div class="box">
                <img src="~/images/phone-icon.png" alt="">
                <h3>our number</h3>
                <a href="tel:1234567890">+123-456-7890</a>
                <a href="tel:1112223333">+111-222-3333</a>
            </div>

        </section>

        <div class="credit">&copy; copyright 2024 by <span>Mr.Axit Gadhiya</span> | all rights reserved!</div>

    </footer>


<div class="loader">
   <img src="~/images/loader.gif" alt="">
</div>

</body>
</html>